import { Router } from 'express'
import { createUser, authenticateUser, createSession, getSessionUser, getUserByDiscordId, setDiscordId, deleteUser } from './users'
import { verifyLinkCode, verifyDeletionCode, assignVerifiedRole } from '@gcpoker/discord'

export const authRouter = Router()

authRouter.post('/signup', (req, res) => {
  try {
    const { username, password } = req.body
    if (!username || !password) {
      return res.status(400).json({ error: 'Username and password required' })
    }
    const user = createUser(username, password)
    const token = createSession(user.id)
    res.json({ token, user: { id: user.id, name: user.name, balance: user.balance } })
  } catch (err: any) {
    res.status(400).json({ error: err.message })
  }
})

authRouter.post('/signin', (req, res) => {
  const { username, password } = req.body
  if (!username || !password) {
    return res.status(400).json({ error: 'Username and password required' })
  }
  const user = authenticateUser(username, password)
  if (!user) {
    return res.status(401).json({ error: 'Invalid username or password' })
  }
  const token = createSession(user.id)
  res.json({ token, user: { id: user.id, name: user.name, balance: user.balance } })
})

authRouter.post('/session', (req, res) => {
  const { token } = req.body
  if (!token) return res.status(400).json({ error: 'Token required' })
  const user = getSessionUser(token)
  if (!user) return res.status(401).json({ error: 'Invalid session' })
  res.json({ user: { id: user.id, name: user.name, balance: user.balance, discordId: user.discordId, discordTag: user.discordTag } })
})

authRouter.post('/discord/link', (req, res) => {
  try {
    const { token, code } = req.body
    if (!token || !code) {
      return res.status(400).json({ error: 'Token and code required' })
    }
    const user = getSessionUser(token)
    if (!user) return res.status(401).json({ error: 'Invalid session' })

    const result = verifyLinkCode(code)
    if (!result) return res.status(400).json({ error: 'Invalid or expired code' })

    const existingUser = getUserByDiscordId(result.discordId)
    if (existingUser && existingUser.id !== user.id) {
      return res.status(409).json({ error: 'Discord account already linked to another user' })
    }

    setDiscordId(user.id, result.discordId, result.discordTag)
    assignVerifiedRole(result.discordId).catch(() => {})
    res.json({ success: true, discordId: result.discordId, discordTag: result.discordTag })
  } catch (err: any) {
    res.status(400).json({ error: err.message })
  }
})

authRouter.post('/discord/status', (req, res) => {
  const { token } = req.body
  if (!token) return res.status(400).json({ error: 'Token required' })
  const user = getSessionUser(token)
  if (!user) return res.status(401).json({ error: 'Invalid session' })
  res.json({ linked: !!user.discordId, discordId: user.discordId, discordTag: user.discordTag })
})

authRouter.post('/discord/unlink', (req, res) => {
  const { token } = req.body
  if (!token) return res.status(400).json({ error: 'Token required' })
  const user = getSessionUser(token)
  if (!user) return res.status(401).json({ error: 'Invalid session' })
  setDiscordId(user.id, '')
  res.json({ success: true })
})

authRouter.post('/delete-account', (req, res) => {
  try {
    const { token, code } = req.body
    if (!token || !code) {
      return res.status(400).json({ error: 'Token and deletion code required' })
    }
    const user = getSessionUser(token)
    if (!user) return res.status(401).json({ error: 'Invalid session' })

    if (!user.discordId) {
      return res.status(400).json({ error: 'You must link a Discord account before deleting. Use the Link Discord option in your profile.' })
    }

    const result = verifyDeletionCode(code)
    if (!result) return res.status(400).json({ error: 'Invalid or expired deletion code' })

    if (user.discordId !== result.discordId) {
      return res.status(403).json({ error: 'Deletion code was generated by a different Discord account' })
    }

    deleteUser(user.id)
    res.json({ success: true })
  } catch (err: any) {
    res.status(400).json({ error: err.message })
  }
})
